// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void InitBar_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_scrMain
void ui_scrMain_screen_init(void);
lv_obj_t * ui_scrMain;
lv_obj_t * ui_Image2;
lv_obj_t * ui_pnlGrup1;
void ui_event_arcGrup1(lv_event_t * e);
lv_obj_t * ui_arcGrup1;
lv_obj_t * ui_lblGrup1;
lv_obj_t * ui_lblGrup1Oran1;
lv_obj_t * ui_pnlGrup2;
void ui_event_arcGrup2(lv_event_t * e);
lv_obj_t * ui_arcGrup2;
lv_obj_t * ui_lblGrup2;
lv_obj_t * ui_lblGrup1Oran2;
lv_obj_t * ui_pnlGrup3;
void ui_event_arcGrup3(lv_event_t * e);
lv_obj_t * ui_arcGrup3;
lv_obj_t * ui_lblGrup3;
lv_obj_t * ui_lblGrup1Oran3;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_lblHexnetTechnology;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_lblLock;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
lv_obj_t * ui_lblSettings;
lv_obj_t * ui_Switch1;
lv_obj_t * ui_pnlGrupSicaklik1;
lv_obj_t * ui_pnlGrupSicaklikResim1;
lv_obj_t * ui_lblPnlGrup1Sicaklik1;
lv_obj_t * ui_lblPnlGrup1SicaklikDeger1;
lv_obj_t * ui_pnlGrupSicaklik2;
lv_obj_t * ui_pnlGrupSicaklikResim2;
lv_obj_t * ui_lblPnlGrup1Sicaklik2;
lv_obj_t * ui_lblPnlGrup1SicaklikDeger2;
lv_obj_t * ui_pnlOutputs;
lv_obj_t * ui_imgBluetoothConnected;
lv_obj_t * ui_lblVangoText;
lv_obj_t * ui_imgsconnected;
lv_obj_t * ui_imgsnotconnected;
lv_obj_t * ui_imgBluetoothNotConnected;
lv_obj_t * ui_imgWForecast;
lv_obj_t * ui_lblDateAndTime;
lv_obj_t * ui_pnlSensors;
lv_obj_t * ui_lblWeather;
lv_obj_t * ui_pnlConnectionLost;
lv_obj_t * ui_Label1;
void ui_event_Button10(lv_event_t * e);
lv_obj_t * ui_Button10;
lv_obj_t * ui_Label6;
lv_obj_t * ui_btnRGBColor;
lv_obj_t * ui_Label7;
// CUSTOM VARIABLES


// SCREEN: ui_scrPanelSettings
void ui_scrPanelSettings_screen_init(void);
lv_obj_t * ui_scrPanelSettings;
lv_obj_t * ui_Panel10;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_lblLock4;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_lblSettings2;
lv_obj_t * ui_pnlSaveConfigs;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label9;
lv_obj_t * ui_pbSaveConfigs;
// CUSTOM VARIABLES


// SCREEN: ui_scrWallpaper
void ui_scrWallpaper_screen_init(void);
lv_obj_t * ui_scrWallpaper;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Label3;
void ui_event_btnUnlockScreen(lv_event_t * e);
lv_obj_t * ui_btnUnlockScreen;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Image5;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Image7;
lv_obj_t * ui_Image8;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Image13;
// CUSTOM VARIABLES


// SCREEN: ui_scrInit
void ui_scrInit_screen_init(void);
lv_obj_t * ui_scrInit;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Image14;
lv_obj_t * ui_brInit;
// CUSTOM VARIABLES


// SCREEN: ui_scrConnectionSettings
void ui_scrConnectionSettings_screen_init(void);
lv_obj_t * ui_scrConnectionSettings;
lv_obj_t * ui_Panel6;
void ui_event_Button13(lv_event_t * e);
lv_obj_t * ui_Button13;
lv_obj_t * ui_lblLock7;
lv_obj_t * ui_arcSensorLevel4;
lv_obj_t * ui_lblSensorLevel4;
lv_obj_t * ui_arcSensorLevel5;
lv_obj_t * ui_lblSensorLevel5;
// CUSTOM VARIABLES


// SCREEN: ui_scrDims
void ui_scrDims_screen_init(void);
lv_obj_t * ui_scrDims;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_lblHexnetTechnology3;
lv_obj_t * ui_Button21;
lv_obj_t * ui_lblLock8;
lv_obj_t * ui_Slider1;
lv_obj_t * ui_lblSettingsB3;
lv_obj_t * ui_Slider2;
lv_obj_t * ui_Slider3;
// CUSTOM VARIABLES


// SCREEN: ui_scrSettings
void ui_scrSettings_screen_init(void);
lv_obj_t * ui_scrSettings;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
void ui_event_Button6(lv_event_t * e);
lv_obj_t * ui_Button6;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
void ui_event_Button9(lv_event_t * e);
lv_obj_t * ui_Button9;
lv_obj_t * ui_Button11;
// CUSTOM VARIABLES


// SCREEN: ui_scrRGB
void ui_scrRGB_screen_init(void);
lv_obj_t * ui_scrRGB;
lv_obj_t * ui_swRGBTurnON;
lv_obj_t * ui_Colorwheel1;
lv_obj_t * ui_btnRGBApply;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_lblHexnetTechnology2;
lv_obj_t * ui_Button7;
lv_obj_t * ui_lblLock2;
lv_obj_t * ui_Label2;
// CUSTOM VARIABLES


// SCREEN: ui_scrTheme
void ui_scrTheme_screen_init(void);
lv_obj_t * ui_scrTheme;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_lblHexnetTechnology4;
void ui_event_Button14(lv_event_t * e);
lv_obj_t * ui_Button14;
lv_obj_t * ui_lblLock3;
lv_obj_t * ui_btnWhiteTheme;
lv_obj_t * ui_btnBlackTheme;
lv_obj_t * ui_swEnableWallpaper;
lv_obj_t * ui_lblSelectTheme;
lv_obj_t * ui_lblWallpaper;
lv_obj_t * ui_rlrTime;
lv_obj_t * ui_lblRolllerTime;
lv_obj_t * ui_lblSettingsB;
// CUSTOM VARIABLES


// SCREEN: ui_scrPages
void ui_scrPages_screen_init(void);
lv_obj_t * ui_scrPages;
void ui_event_Button20(lv_event_t * e);
lv_obj_t * ui_Button20;
lv_obj_t * ui_Button12;
void ui_event_Button15(lv_event_t * e);
lv_obj_t * ui_Button15;
void ui_event_Button16(lv_event_t * e);
lv_obj_t * ui_Button16;
void ui_event_Button17(lv_event_t * e);
lv_obj_t * ui_Button17;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_arc[1] = {&ui_img_arc1_png};
const lv_img_dsc_t * ui_imgset_btnsettings[1] = {&ui_img_btnsettings2_png};
const lv_img_dsc_t * ui_imgset_logo[1] = {&ui_img_logo3_png};
const lv_img_dsc_t * ui_imgset_outcontrols[1] = {&ui_img_outcontrols2_png};
const lv_img_dsc_t * ui_imgset_weatherforecast[1] = {&ui_img_weatherforecast2_png};
const lv_img_dsc_t * ui_imgset_wifi[1] = {&ui_img_wifi3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void InitBar_Animation(lv_obj_t * TargetObject, int delay)
{

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_arcGrup1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        arcTemizSuValueChanged(e);
    }
}

void ui_event_arcGrup2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        arcTemizSuValueChanged(e);
    }
}

void ui_event_arcGrup3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        arcTemizSuValueChanged(e);
    }
}

void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrPages, LV_SCR_LOAD_ANIM_MOVE_TOP, 100, 0, &ui_scrPages_screen_init);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrSettings, LV_SCR_LOAD_ANIM_FADE_ON, 150, 0, &ui_scrSettings_screen_init);
    }
}

void ui_event_Button10(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_pnlConnectionLost, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_scrMain_screen_init);
    }
}

void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        savePanelSettings(e);
    }
}

void ui_event_btnUnlockScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_OVER_TOP, 500, 0, &ui_scrMain_screen_init);
    }
}

void ui_event_Button13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_scrMain_screen_init);
    }
}

void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrPanelSettings, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_scrPanelSettings_screen_init);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrWallpaper, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 200, 0, &ui_scrWallpaper_screen_init);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrTheme, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrTheme_screen_init);
    }
}

void ui_event_Button9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrConnectionSettings, LV_SCR_LOAD_ANIM_OVER_RIGHT, 200, 0,
                          &ui_scrConnectionSettings_screen_init);
    }
}

void ui_event_Button14(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrMain, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_scrMain_screen_init);
    }
}

void ui_event_Button20(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrDims, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 200, 0, &ui_scrDims_screen_init);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrConnectionSettings, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrConnectionSettings_screen_init);
    }
}

void ui_event_Button16(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrConnectionSettings, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_scrConnectionSettings_screen_init);
    }
}

void ui_event_Button17(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_scrRGB, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_scrRGB_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_scrMain_screen_init();
    ui_scrPanelSettings_screen_init();
    ui_scrWallpaper_screen_init();
    ui_scrInit_screen_init();
    ui_scrConnectionSettings_screen_init();
    ui_scrDims_screen_init();
    ui_scrSettings_screen_init();
    ui_scrRGB_screen_init();
    ui_scrTheme_screen_init();
    ui_scrPages_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_scrMain);
}
