// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_scrPanelSettings = NULL;
lv_obj_t * ui_pnlSaveConfigs = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_pbSaveConfigs = NULL;
// event funtions

// build funtions

void ui_scrPanelSettings_screen_init(void)
{
    ui_scrPanelSettings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_scrPanelSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scrPanelSettings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scrPanelSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pnlSaveConfigs = lv_obj_create(ui_scrPanelSettings);
    lv_obj_set_width(ui_pnlSaveConfigs, 545);
    lv_obj_set_height(ui_pnlSaveConfigs, 125);
    lv_obj_set_x(ui_pnlSaveConfigs, -14);
    lv_obj_set_y(ui_pnlSaveConfigs, -29);
    lv_obj_set_align(ui_pnlSaveConfigs, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_pnlSaveConfigs, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_pnlSaveConfigs, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_pnlSaveConfigs, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pnlSaveConfigs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_pnlSaveConfigs, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_pnlSaveConfigs, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_pnlSaveConfigs, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_pnlSaveConfigs, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_pnlSaveConfigs, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_pnlSaveConfigs, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_pnlSaveConfigs, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_pnlSaveConfigs, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_pnlSaveConfigs);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -2);
    lv_obj_set_y(ui_Label12, -12);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "SAVING CONFIGURATIONS...\n   DEVICE WILL RESTART");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_pnlSaveConfigs);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, -2);
    lv_obj_set_y(ui_Label9, 25);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "CLOSE");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pbSaveConfigs = lv_bar_create(ui_pnlSaveConfigs);
    lv_obj_set_width(ui_pbSaveConfigs, 173);
    lv_obj_set_height(ui_pbSaveConfigs, 10);
    lv_obj_set_x(ui_pbSaveConfigs, -2);
    lv_obj_set_y(ui_pbSaveConfigs, 39);
    lv_obj_set_align(ui_pbSaveConfigs, LV_ALIGN_CENTER);

}

void ui_scrPanelSettings_screen_destroy(void)
{
    if(ui_scrPanelSettings) lv_obj_del(ui_scrPanelSettings);

    // NULL screen variables
    ui_scrPanelSettings = NULL;
    ui_pnlSaveConfigs = NULL;
    ui_Label12 = NULL;
    ui_Label9 = NULL;
    ui_pbSaveConfigs = NULL;

}
